require('preset')
require('plugins')
require('bindings')
require('config-telescope')
require('config-treesitter')
require('config-lualine')
require('config-hop')
require('config-dap')
require('config-coc')
-- require('config-lsp')
require('config-formatter')
require('config-oil')

-- require('config-neorg')

